-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_user_id uuid NOT NULL,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  description text,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role text NOT NULL,
  department text NOT NULL,
  resource text NOT NULL,
  actions jsonb NOT NULL DEFAULT '{"view": false, "create": false, "delete": false, "export": false, "update": false}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['ceo'::text, 'admin'::text, 'manager'::text, 'agent'::text, 'super_admin'::text, 'viewer'::text])),
  permissions jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  department text DEFAULT 'executive'::text CHECK (department = ANY (ARRAY['executive'::text, 'sales'::text, 'support'::text, 'operations'::text, 'finance'::text, 'analytics'::text, 'product'::text])),
  full_name text,
  phone text,
  avatar_url text,
  last_login_ip inet,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])),
  old_data jsonb,
  new_data jsonb,
  changed_fields ARRAY,
  platform text NOT NULL,
  device_id text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bills_of_lading (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  receiver_name text NOT NULL,
  receiver_signature_url text,
  delivery_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  notes text DEFAULT ''::text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'signed'::text, 'sent'::text, 'confirmed'::text])),
  broker_email text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bills_of_lading_pkey PRIMARY KEY (id),
  CONSTRAINT bills_of_lading_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT bills_of_lading_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bol_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bol_id uuid NOT NULL,
  document_url text NOT NULL,
  document_type text DEFAULT 'photo'::text CHECK (document_type = ANY (ARRAY['photo'::text, 'pdf'::text, 'scan'::text])),
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bol_documents_pkey PRIMARY KEY (id),
  CONSTRAINT bol_documents_bol_id_fkey FOREIGN KEY (bol_id) REFERENCES public.bills_of_lading(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role text CHECK (role = ANY (ARRAY['broker'::text, 'dispatcher'::text, 'shipper'::text, 'receiver'::text, 'fleet_owner'::text, 'other'::text, NULL::text])),
  company text,
  mc_number text,
  favorite boolean DEFAULT false,
  blocked boolean DEFAULT false,
  notes text,
  workspace_id uuid,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT contacts_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.driver_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  expense_type text NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  description text,
  receipt_url text,
  receipt_type text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_from text DEFAULT 'mobile'::text,
  device_id text,
  CONSTRAINT driver_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT driver_expenses_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT driver_expenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driving_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  load_id uuid,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  miles_driven numeric DEFAULT 0,
  start_location text,
  end_location text,
  notes text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driving_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT driving_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT driving_sessions_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id)
);
CREATE TABLE public.generated_pdfs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  pdf_url text NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT generated_pdfs_pkey PRIMARY KEY (id),
  CONSTRAINT generated_pdfs_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT generated_pdfs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ifta_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  load_id uuid,
  state_code text NOT NULL,
  miles_driven numeric NOT NULL DEFAULT 0,
  gallons_purchased numeric DEFAULT 0,
  fuel_cost numeric DEFAULT 0,
  date date NOT NULL DEFAULT CURRENT_DATE,
  quarter integer NOT NULL CHECK (quarter >= 1 AND quarter <= 4),
  year integer NOT NULL,
  notes text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ifta_records_pkey PRIMARY KEY (id),
  CONSTRAINT ifta_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT ifta_records_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id)
);
CREATE TABLE public.load_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_id uuid NOT NULL,
  event_type text NOT NULL,
  event_location text NOT NULL CHECK (event_location = ANY (ARRAY['shipper'::text, 'receiver'::text, 'in_transit'::text])),
  latitude double precision,
  longitude double precision,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_from text DEFAULT 'mobile'::text,
  device_id text,
  CONSTRAINT load_events_pkey PRIMARY KEY (id),
  CONSTRAINT load_events_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id)
);
CREATE TABLE public.load_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  note_text text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_from text DEFAULT 'mobile'::text,
  device_id text,
  CONSTRAINT load_notes_pkey PRIMARY KEY (id),
  CONSTRAINT load_notes_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT load_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.load_photos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  photo_url text NOT NULL,
  caption text,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_from text DEFAULT 'mobile'::text,
  device_id text,
  CONSTRAINT load_photos_pkey PRIMARY KEY (id),
  CONSTRAINT load_photos_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT load_photos_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.load_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  load_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  shared_with_user uuid,
  shared_with_workspace uuid,
  share_type text NOT NULL DEFAULT 'manual'::text CHECK (share_type = ANY (ARRAY['manual'::text, 'auto'::text, 'requested'::text])),
  permissions jsonb DEFAULT '{"can_view": true, "can_export": true, "can_view_notes": true, "can_view_photos": true, "can_view_expenses": false}'::jsonb,
  expires_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  viewed_at timestamp with time zone,
  view_count integer DEFAULT 0,
  CONSTRAINT load_shares_pkey PRIMARY KEY (id),
  CONSTRAINT load_shares_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT load_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES auth.users(id),
  CONSTRAINT load_shares_shared_with_user_fkey FOREIGN KEY (shared_with_user) REFERENCES auth.users(id),
  CONSTRAINT load_shares_shared_with_workspace_fkey FOREIGN KEY (shared_with_workspace) REFERENCES public.workspaces(id)
);
CREATE TABLE public.load_voice_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  audio_url text NOT NULL,
  transcription text,
  duration_seconds integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT load_voice_notes_pkey PRIMARY KEY (id),
  CONSTRAINT load_voice_notes_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT load_voice_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.loads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'canceled'::text])),
  shipper_address text NOT NULL,
  shipper_lat double precision,
  shipper_lng double precision,
  appointment_time_shipper timestamp with time zone,
  receiver_address text NOT NULL,
  receiver_lat double precision,
  receiver_lng double precision,
  appointment_time_receiver timestamp with time zone,
  detention_pay_enabled boolean NOT NULL DEFAULT false,
  detention_after_hours double precision DEFAULT 2.0,
  rate_confirmation_miles double precision,
  broker_contact_id text,
  deadhead_miles_gps double precision DEFAULT 0,
  loaded_miles_gps double precision DEFAULT 0,
  total_detention_minutes_shipper integer DEFAULT 0,
  total_detention_minutes_receiver integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  truck_number text,
  trailer_number text,
  trailer_type text,
  second_trailer_number text,
  third_trailer_number text,
  dolly_number text,
  cargo_weight numeric,
  dispatcher_contact_id text,
  rate_confirmation_type text DEFAULT 'per_mile'::text,
  rate_confirmation_amount numeric,
  payment_amount numeric,
  payment_type text DEFAULT 'per_mile'::text,
  deadhead_miles numeric CHECK (deadhead_miles IS NULL OR deadhead_miles >= 0::numeric),
  empty_miles numeric,
  temperature text,
  target_rate_per_mile numeric DEFAULT 2.00,
  actual_rate_per_mile numeric,
  total_revenue numeric,
  net_profit numeric,
  rate numeric,
  total_miles numeric,
  created_from text DEFAULT 'mobile'::text,
  updated_from text,
  device_id text,
  last_synced_at timestamp with time zone DEFAULT now(),
  sync_status text DEFAULT 'synced'::text CHECK (sync_status = ANY (ARRAY['synced'::text, 'pending'::text, 'conflict'::text, 'failed'::text])),
  operation_type text DEFAULT 'live_load_unload'::text CHECK (operation_type = ANY (ARRAY['live_load_unload'::text, 'drop_hook'::text])),
  drop_trailer_number text,
  hook_trailer_number text,
  auto_complete_pending boolean DEFAULT false,
  auto_complete_triggered_at timestamp with time zone,
  auto_complete_speed_detected numeric,
  auto_complete_confirmed boolean DEFAULT false,
  auto_complete_denied boolean DEFAULT false,
  drop_location_code text,
  drop_location_name text,
  drop_location_type text CHECK (drop_location_type = ANY (ARRAY['hub'::text, 'yard'::text, 'gas_station'::text, 'truck_stop'::text, 'customer_facility'::text, 'parking_lot'::text, 'meet_point'::text, 'other'::text])),
  hook_location_code text,
  hook_location_name text,
  hook_location_type text CHECK (hook_location_type = ANY (ARRAY['hub'::text, 'yard'::text, 'gas_station'::text, 'truck_stop'::text, 'customer_facility'::text, 'parking_lot'::text, 'meet_point'::text, 'other'::text])),
  swap_driver_name text,
  swap_driver_contact text,
  CONSTRAINT loads_pkey PRIMARY KEY (id),
  CONSTRAINT loads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.mc_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  workspace_id uuid,
  mc_number text,
  dot_number text,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['verified'::text, 'pending'::text, 'failed'::text])),
  verification_data jsonb DEFAULT '{}'::jsonb,
  error_message text,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mc_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT mc_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT mc_verifications_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.pending_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  load_id uuid NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['auto_complete_load'::text, 'detention_alert'::text, 'speed_alert'::text, 'general'::text])),
  title text NOT NULL,
  message text NOT NULL,
  action_required boolean DEFAULT true,
  action_options jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'responded'::text, 'expired'::text, 'cancelled'::text])),
  expires_at timestamp with time zone NOT NULL,
  responded_at timestamp with time zone,
  response_action text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pending_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT pending_notifications_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT pending_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pricing_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  version text NOT NULL UNIQUE,
  config jsonb NOT NULL,
  effective_date timestamp with time zone NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT false,
  notes text,
  CONSTRAINT pricing_configs_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  phone text,
  company_name text,
  truck_number text,
  subscription_tier text NOT NULL DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text, 'pro_annual'::text])),
  subscription_status text NOT NULL DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'trialing'::text])),
  stripe_customer_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_trailer_number text,
  default_trailer_type text,
  theme_preference text DEFAULT 'system'::text CHECK (theme_preference = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
  has_seen_onboarding boolean DEFAULT false,
  profile_photo_url text,
  avatar_url text,
  referral_code text UNIQUE,
  referred_by_code text,
  total_referrals integer DEFAULT 0,
  referral_rewards numeric DEFAULT 0,
  role text DEFAULT 'driver'::text CHECK (role = ANY (ARRAY['driver'::text, 'dispatcher'::text, 'broker'::text, 'fleet_owner'::text, 'company'::text])),
  operating_authority_mode text DEFAULT 'own'::text CHECK (operating_authority_mode = ANY (ARRAY['own'::text, 'under_other'::text])),
  operating_authority_company text,
  operating_authority_mc text,
  affiliation_mode text DEFAULT 'independent'::text CHECK (affiliation_mode = ANY (ARRAY['independent'::text, 'affiliated'::text])),
  affiliated_company_name text,
  workspace_id uuid,
  mc_number text,
  dot_number text,
  fleet_size text CHECK (fleet_size = ANY (ARRAY['1-5'::text, '6-10'::text, '11-20'::text, '21-50'::text, '51-100'::text, '100+'::text])),
  verified boolean DEFAULT false,
  verification_method text CHECK (verification_method = ANY (ARRAY['mc_lookup'::text, 'company_invite'::text, 'admin_approval'::text, 'manual'::text])),
  verification_date timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.rate_confirmations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  load_id uuid,
  user_id uuid NOT NULL,
  document_url text NOT NULL,
  extracted_data jsonb DEFAULT '{}'::jsonb,
  verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rate_confirmations_pkey PRIMARY KEY (id),
  CONSTRAINT rate_confirmations_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT rate_confirmations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referred_id uuid NOT NULL,
  referral_code text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text])),
  reward_granted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.scale_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  load_id uuid NOT NULL,
  user_id uuid NOT NULL,
  ticket_url text NOT NULL,
  weight_gross numeric NOT NULL,
  weight_tare numeric NOT NULL,
  weight_net numeric NOT NULL,
  location text NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  notes text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scale_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT scale_tickets_load_id_fkey FOREIGN KEY (load_id) REFERENCES public.loads(id),
  CONSTRAINT scale_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_billing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  billing_period_start timestamp with time zone NOT NULL,
  billing_period_end timestamp with time zone NOT NULL,
  total_drivers integer NOT NULL DEFAULT 0,
  active_drivers integer NOT NULL DEFAULT 0,
  pricing_config_version text NOT NULL,
  tier_name text NOT NULL,
  price_per_driver numeric NOT NULL,
  base_price numeric,
  subtotal numeric NOT NULL,
  tax numeric DEFAULT 0,
  total numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'cancelled'::text, 'refunded'::text])),
  stripe_invoice_id text,
  paid_at timestamp with time zone,
  calculation_details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_billing_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_billing_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  stripe_subscription_id text UNIQUE,
  stripe_customer_id text NOT NULL,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['pro_monthly'::text, 'pro_annual'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'trialing'::text, 'incomplete'::text, 'incomplete_expired'::text, 'unpaid'::text])),
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT suggestions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  screenshots ARRAY DEFAULT '{}'::text[],
  user_email text,
  user_name text,
  device_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.sync_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_id text NOT NULL,
  platform text NOT NULL,
  sync_type text NOT NULL CHECK (sync_type = ANY (ARRAY['full'::text, 'partial'::text, 'conflict_resolution'::text])),
  table_name text NOT NULL,
  record_count integer NOT NULL DEFAULT 0,
  success boolean NOT NULL DEFAULT true,
  error_message text,
  sync_started_at timestamp with time zone NOT NULL DEFAULT now(),
  sync_completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_log_pkey PRIMARY KEY (id),
  CONSTRAINT sync_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.team_drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  primary_driver_id uuid NOT NULL,
  secondary_driver_id uuid NOT NULL,
  truck_id text,
  active boolean DEFAULT true,
  shared_access boolean DEFAULT true,
  sync_loads boolean DEFAULT true,
  sync_expenses boolean DEFAULT true,
  sync_documents boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_drivers_pkey PRIMARY KEY (id),
  CONSTRAINT team_drivers_primary_driver_id_fkey FOREIGN KEY (primary_driver_id) REFERENCES auth.users(id),
  CONSTRAINT team_drivers_secondary_driver_id_fkey FOREIGN KEY (secondary_driver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.voice_commands_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  command_type text NOT NULL,
  command_text text,
  executed_at timestamp with time zone DEFAULT now(),
  success boolean DEFAULT true,
  error_message text,
  CONSTRAINT voice_commands_log_pkey PRIMARY KEY (id),
  CONSTRAINT voice_commands_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workspace_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'dispatcher'::text, 'viewer'::text])),
  permissions jsonb DEFAULT '{"auto_sync": false, "can_export": false, "can_invite": false, "can_view_loads": true, "can_view_expenses": false, "can_view_documents": true}'::jsonb,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'pending'::text, 'suspended'::text])),
  joined_at timestamp with time zone DEFAULT now(),
  invited_by uuid,
  invitation_accepted_at timestamp with time zone,
  last_activity_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workspace_members_pkey PRIMARY KEY (id),
  CONSTRAINT workspace_members_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT workspace_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workspace_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.workspaces (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['fleet'::text, 'company'::text, 'brokerage'::text, 'dispatch_service'::text])),
  mc_number text,
  dot_number text,
  operating_authority_mode text DEFAULT 'own'::text CHECK (operating_authority_mode = ANY (ARRAY['own'::text, 'under_other'::text])),
  operating_authority_company text,
  operating_authority_mc text,
  verified boolean DEFAULT false,
  verification_method text CHECK (verification_method = ANY (ARRAY['mc_lookup'::text, 'admin_approval'::text, 'manual'::text, NULL::text])),
  verification_date timestamp with time zone,
  owner_id uuid NOT NULL,
  settings jsonb DEFAULT '{"max_members": null, "invite_link_enabled": true, "auto_approve_members": true, "require_manual_approval": false, "default_member_permissions": {"auto_sync": false, "can_export": false, "can_view_loads": true, "can_view_expenses": false, "can_view_documents": true}}'::jsonb,
  logo_url text,
  description text,
  website text,
  billing_email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT workspaces_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
